# Generated by Django 4.0.4 on 2022-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='correct',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='total_questions',
            field=models.IntegerField(null=True),
        ),
    ]
